export const getStyles = () => `
:host{--of-primary-color:#2563eb;--of-accent-color:#7c3aed;--of-accent-color-2:#06b6d4;--of-gradient:linear-gradient(135deg,var(--of-primary-color),var(--of-accent-color),var(--of-accent-color-2));--of-gradient-soft:linear-gradient(135deg,color-mix(in oklab,var(--of-primary-color) 22%,transparent),color-mix(in oklab,var(--of-accent-color) 18%,transparent));--of-bg:#0b0f19;--of-bg-elevated:#101828;--of-panel-bg:rgba(255,255,255,.03);--of-text:#e6ecff;--of-text-muted:#9fb0d1;--of-heading:#f8fbff;--of-border:rgba(255,255,255,.1);--of-shadow:0 20px 50px rgba(0,0,0,.35);--of-link:color-mix(in oklab,var(--of-primary-color) 82%,white);--of-link-hover:color-mix(in oklab,var(--of-accent-color) 70%,white);--of-radius:14px;--of-radius-lg:20px;--of-max-width:1400px;--of-font-family:Inter,ui-sans-serif,system-ui,sans-serif;--of-column-gap:28px;--of-row-gap:20px;--of-padding:42px 24px;--of-gap:16px;--of-brand-image-size:52px;--of-brand-image-radius:var(--of-radius);--of-brand-message-max-width:38rem;display:block}
:host([theme="light"]){--of-bg:#f8fafc;--of-bg-elevated:#fff;--of-panel-bg:rgba(255,255,255,.75);--of-text:#182132;--of-text-muted:#55657f;--of-heading:#0f172a;--of-border:rgba(15,23,42,.12);--of-shadow:0 14px 35px rgba(15,23,42,.08)}
:host([theme="minimal"]){--of-bg:transparent;--of-panel-bg:transparent;--of-shadow:none;--of-border:rgba(128,128,128,.2)}
.wrap{background:var(--of-bg);background-image:var(--of-gradient-soft);color:var(--of-text);font-family:var(--of-font-family);border-top:1px solid var(--of-border)}
:host([background-style="solid"]) .wrap{background-image:none}
:host([background-style="gradient"]) .wrap{background-image:var(--of-gradient-soft)}
:host([background-style="mesh"]) .wrap{background-image:radial-gradient(900px 300px at 10% 0%,color-mix(in oklab,var(--of-primary-color) 26%,transparent),transparent),radial-gradient(900px 300px at 95% 5%,color-mix(in oklab,var(--of-accent-color) 22%,transparent),transparent)}
:host([background-style="minimal"]) .wrap{background-image:none}
.inner{max-width:var(--of-max-width);margin:0 auto;padding:var(--of-padding);display:grid;gap:var(--of-row-gap)}
.layout{display:grid;gap:var(--of-row-gap)}
.layout.simple,.layout.columns-brand,.layout.newsletter{grid-template-columns:minmax(280px,1fr) 2fr;align-items:start}
.layout.centered{text-align:center}.layout.centered .openfooter-brand-main{justify-content:center;text-align:center}
.inline-links{display:flex;flex-wrap:wrap;gap:12px}.inline-links.centered{justify-content:center}
.grid.columns{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:var(--of-row-gap) var(--of-column-gap)}
section{background:var(--of-panel-bg);backdrop-filter:blur(8px);border:1px solid var(--of-border);border-radius:var(--of-radius);padding:14px 14px 12px;box-shadow:var(--of-shadow)}
h3,h4{margin:0 0 8px;color:var(--of-heading);letter-spacing:.01em}h4{font-size:.92rem;text-transform:uppercase;opacity:.9}
a{color:var(--of-link);text-decoration:none;transition:color 180ms ease,background 180ms ease,border-color 180ms ease,transform 180ms ease}a:hover{color:var(--of-link-hover);transform:translateY(-1px)}
.small{font-size:.88rem;color:var(--of-text-muted)} ul{list-style:none;padding:0;margin:0;display:grid;gap:8px}
.social-row{display:flex;gap:10px;flex-wrap:wrap}.social-link{padding:7px 11px;border:1px solid var(--of-border);border-radius:999px;background:var(--of-panel-bg)}
.openfooter-brand{display:grid;gap:8px}.openfooter-brand-main{display:flex;gap:12px;align-items:flex-start;padding:10px;border-radius:var(--of-radius-lg);background:var(--of-panel-bg);border:1px solid var(--of-border);box-shadow:var(--of-shadow)}.openfooter-brand-image{width:var(--of-brand-image-size);height:var(--of-brand-image-size);object-fit:cover;border:1px solid var(--of-border)}.openfooter-brand-image.shape-circle{border-radius:999px}.openfooter-brand-image.shape-rounded{border-radius:var(--of-brand-image-radius)}.openfooter-brand-image.shape-square{border-radius:0}.openfooter-brand-name{font-weight:700;font-size:1.03rem}.openfooter-brand-tagline{color:var(--of-text-muted)}.openfooter-brand-message{max-width:var(--of-brand-message-max-width);color:var(--of-text-muted)}
.newsletter{padding:18px;border-radius:var(--of-radius-lg);background:linear-gradient(135deg,color-mix(in oklab,var(--of-primary-color) 16%,transparent),color-mix(in oklab,var(--of-accent-color) 12%,transparent));}.newsletter form{display:flex;gap:8px;flex-wrap:wrap}.newsletter input{padding:10px 12px;border-radius:10px;border:1px solid var(--of-border);background:var(--of-bg-elevated);color:var(--of-text)}.newsletter button{padding:10px 14px;border-radius:10px;border:1px solid transparent;background:var(--of-gradient);color:#fff}
@media (max-width: 900px){.layout.simple,.layout.columns-brand,.layout.newsletter{grid-template-columns:1fr}}
`;
